name: Documentation Issue
description: Report an issue or suggest improvements to project documentation.
title: '[Documentation]: Brief description of the documentation issue'
labels: [documentation]

body:
  - type: markdown
    attributes:
      value: |
        ## Before You Continue
        Please take a moment to search our existing issues to ensure that a similar documentation issue hasn't already been reported.

  - type: checkboxes
    attributes:
      label: I confirm that I searched through the issues and didn't find my documentation issue.
      options:
        - label: Confirm
          required: true

  - type: textarea
    id: description
    attributes:
      label: Documentation Issue Description
      description: |
        Briefly describe the issue with the documentation or suggest improvements. 
        Include specific details such as the page or section affected and what needs to be clarified or corrected.
      placeholder: 'Example: The getting started in push chat lacks instructions for setting up the wallet.'
      required: true

  - type: textarea
    id: suggested_improvements
    attributes:
      label: Suggested Improvements
      description: |
        If applicable, provide any suggestions or proposed changes to improve the documentation. 
        Be specific and include any additional information that could help in addressing the issue.
      placeholder: 'Example: Add a wallet setup section to address common errors.'
